# Generated by Django 5.1.6 on 2025-03-13 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What's the name of this character?", max_length=255
                    ),
                ),
                (
                    "org_play_suffix",
                    models.IntegerField(
                        default=2001,
                        help_text="What's the unique identifier for this character?",
                    ),
                ),
                ("gold", models.IntegerField(default=0)),
                ("experience", models.IntegerField(default=0)),
                (
                    "profile",
                    models.TextField(
                        blank=True,
                        help_text="Include character description, background and notes here",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Who is playing this character?",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
