# Generated by Django 5.1.6 on 2025-03-17 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="org_play_suffix",
            new_name="character_number",
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.UniqueConstraint(
                fields=("player", "character_number"),
                name="unique_player_character_number",
            ),
        ),
    ]
