# Generated by Django 5.1.6 on 2025-03-19 22:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_org_play_suffix_character_character_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='character',
            field=models.ForeignKey(help_text='Which character has played this scenario?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario', to='tracker.character'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='gold_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='How much gold was earned. Include your Earned Income. Represent Silver and Copper as decimal values. For Platinum, multiply by 10. MOVE TO CHRONICLE', max_digits=5),
        ),
        migrations.AddField(
            model_name='scenario',
            name='name',
            field=models.CharField(blank=True, help_text="What's the name of this scenario?", max_length=256),
        ),
        migrations.AddField(
            model_name='scenario',
            name='notes',
            field=models.TextField(blank=True, help_text='various textual data you want to store; now for results for Recall Knowledge checks. MOVE TO JOURNAL', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='number',
            field=models.CharField(blank=True, help_text='How is this scenario identified? 1-01? 6-05?', max_length=25),
        ),
        migrations.AddField(
            model_name='scenario',
            name='other_url',
            field=models.URLField(blank=True, help_text='Where can reference to this be found outside the Paizo site? One of the community wikis, for example.', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='paizo_url',
            field=models.URLField(blank=True, help_text='Where can this be found on the Paizo site?', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='repeatable',
            field=models.BooleanField(default=False, help_text='Is this repeatable'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='starfinder',
            field=models.BooleanField(default=False, help_text='Is this a Starfinder Society scenario?'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, help_text='What tags (other than repeatable) does this scenario have', size=None),
        ),
        migrations.AddField(
            model_name='scenario',
            name='xp_earned',
            field=models.IntegerField(default=0, help_text='How many Experience Points were earned. MOVE TO CHRONICLE'),
        ),
    ]
