# Generated by Django 5.1.6 on 2025-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_scenario_character_scenario_gold_earned_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('character', 'number'), name='unique_character_number'),
        ),
    ]
